import type { Metadata } from "next";
import "./globals.css";
import { textFont } from "./ui/fonts";

export const metadata: Metadata = {
  title: "Rick & Morty funlib",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body
        className={`${textFont.className} flex justify-center antialiased h-screen bg-[url('https://feji.us/a1ypi1')] bg-cover bg-center`}
      >
        {children}
      </body>
    </html>
  );
}
